routes/web.php
<?php

use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\admin\TariffController;
use App\Http\Controllers\admin\OrderController;
use App\Http\Controllers\admin\ReportController;
use App\Http\Controllers\admin\CompanyInfoController;
use App\Http\Controllers\admin\TransactionController;
use App\Http\Controllers\admin\BookingController;
use App\Http\Controllers\admin\RecieptController;
use App\Http\Controllers\admin\ReservationController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\ImageGalleryController;
use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
    Route::group(['middleware' => 'HtmlMinifier'], function () {

        Route::get('/', [IndexController::class, 'index'])->name('index');

        Route::get('gallery', [ImageGalleryController::class, 'index'])->name('gallery');

        Route::get('explore', [IndexController::class, 'explore'])->name('explore');

        Route::get('tariff', [IndexController::class, 'tariff'])->name('tariff');

        Route::get('inquiry/{t_id}', [IndexController::class, 'bookingInquery'])->name('inquiry');

        Route::get('contactus', [IndexController::class, 'contactus'])->name('contactus');

        Route::get('thankyou', function () {
            return view('thankyou');
        })->name('thankyou');

        Route::prefix('book')->group(function () {
            Route::get('', [BookingController::class, 'index'])->name('bookingEngine');
            Route::post('user-details', [BookingController::class, 'userDetails'])->name('bookingEngine.user.details');
            Route::get('search', [BookingController::class, ''])->name('bookingEngine.room');
            Route::post('search-room', [BookingController::class, ''])->name('bookingEngine.room.save');
            Route::post('paytm-payment', [BookingController::class, 'paytmPayment'])->name('paytm.payment');
            Route::post('paytm-callback', [BookingController::class, 'paytmCallback'])->name('paytm.callback');
        });
    });


    // Route::get('contactus/reload-captcha', [IndexController::class, 'reloadCaptcha'])->name('contactus.captcha-reload');

    Route::post('contactus/save', [IndexController::class, 'savecontactUsData'])->name('contactus.save');

    Route::post('inquiry/{t_id}/save', [IndexController::class, 'bookingInquerySave'])->name('inquiry.save');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

    Route::prefix('dashboard')->middleware(['auth'])->group(function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

        // Staff Admin
        Route::middleware(['role:admin'])->group(function () {
            Route::get('product/list', [DashboardController::class, 'productlist'])->name('dashboard.products.list');
            Route::get('transaction', [TransactionController::class, 'index'])->name('dashboard.transaction.index');
            Route::get('transaction/create', [TransactionController::class, 'linkGenerate'])->name('dashboard.transaction.link.create');
            // Route::get('food/receipt/', [RecieptController::class, 'index'])->name('dashboard.receipt.index');

            Route::resource('company-info', CompanyInfoController::class);
            Route::prefix('receipt')->group(function () {
                // Route::get('reservation/{reservationId}', [ReservationController::class, 'show'])->name('dashboard.receipt.reservation.show');

                // Route::get('room/{bookingId}', [RecieptController::class, 'roomshow'])->name('dashboard.receipt.room.show');
            });

            Route::prefix('reservation')->group(function () {
                Route::get('', [ReservationController::class, 'index'])->name('dashboard.reservation.list');
                Route::get('new', [ReservationController::class, 'create'])->name('dashboard.reservation.new');
                Route::post('create', [ReservationController::class, 'store'])->name('dashboard.reservation.create');
                Route::get('{reservationId}', [ReservationController::class, 'show'])->name('dashboard.receipt.reservation.show');
                Route::get('room/receipt/{id}', [RecieptController::class, 'roomshow'])->name('dashboard.receipt.room.bill');
            });

            Route::resource('stocks', StockController::class);
        });

        // Staff Manager
        Route::middleware(['role:manager'])->group(function (){

        });

        // Staff Routes
        Route::middleware(['role:staff'])->group(function (){

        });

        Route::middleware(['role:admin|manager'])->group(function() {
            Route::get('gallery', [ImageGalleryController::class, 'index'])->name('dashboard.gallery.view');
            Route::get('gallery/create', [ImageGalleryController::class, 'create'])->name('dashboard.gallery.create');
            Route::post('gallery/store', [ImageGalleryController::class, 'upload'])->name('dashboard.gallery.upload');
        });

        Route::middleware(['role:admin|staff'])->group(function() {
            Route::resource('order', OrderController::class); // order.index
            Route::get('food/{foodId}', [RecieptController::class, 'show'])->name('dashboard.receipt.food.show');
            // Route::get('order/list/all', [OrderController::class, 'listOrder'])->name('dashboard.order.table');
            // Route::get('receipt', [ReportController::class, 'receiptShow'])->name('order.receipt');
        });

        Route::middleware(['role:admin|manager|staff'])->group(function() {
            Route::get('profile', [DashboardController::class, 'myprofile'])->name('dashboard.profile');
            Route::resource('tariff', TariffController::class);
        });

    });

    require __DIR__ . '/auth.php';

app/Models/Stock.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    use HasFactory;

    protected $table = "stocks";
    protected $fillable = [
        'stock_name', 'description', 'brand', 'price', 'quantity', 'alert_stock'
    ];
}

app/Http/Controllers/StockController.php
<?php

namespace App\Http\Controllers;

use App\Models\Stock;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class StockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $stockList = Stock::get();
        return view('modules.stocks.index' , compact('stockList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $stockList = Stock::get();
        return view('modules.stocks.addstock' , compact('stockList'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request);
        // Str::ucfirst($testString);
        Stock::create([
            'stock_name' => Str::ucfirst($request->stock_name),
            'description' => 'Added Stock',
            'brand' => Str::ucfirst($request->brand),
            'price' => $request->price,
            'quantity' => $request->quantity,
            'alert_stock' => '10'
        ]);
        return redirect()->route('stocks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function show(Stock $stock)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function edit(Stock $stock)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Stock $stock)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Stock  $stock
     * @return \Illuminate\Http\Response
     */
    public function destroy(Stock $stock)
    {
        //
    }

    public function autoComplete(Request $request) {
        $query = $request->get('term','');

        $products=Stock::where('stock_name','LIKE','%'.$query.'%')->get();

        $data=array();
        foreach ($products as $product) {
                $data[]=array('value'=>$product->stock_name,'id'=>$product->id);
        }
        if(count($data))
             return $data;
        else
            return ['value'=>'','id'=>''];
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/modules/stocks/addstock.blade.php
<x-app-layout>
    <x-slot name="header">
        {{-- <link href="http://demo.expertphp.in/css/jquery.ui.autocomplete.css" rel="stylesheet"> --}}
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Stocks List') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('stocks.store') }}" method="post">
                        @csrf
                        {{-- {!! Form::text('search_text', null, array('placeholder' => 'Search Text','class' => 'form-control','id'=>'search_text')) !!} --}}
                        {{-- <input type="text" placeholder="Search Text" class="form-control" id="search_text" /> --}}
                        <div class="form-group">
                            <label for="paystatus_id">Stock Name</label>
                            <input id="seed_one" type="text" name="stock_name"/>
                        </div>
                        <div class="form-group">
                            <label for="paystatus_id">Stock Brand</label>
                            <input type="text" name="brand"/>
                        </div>
                        <div class="form-group">
                            <label for="paystatus_id">Stock Price</label>
                            <input type="number" min="0.00" max="10000.00" step="0.01" name="price"/>
                        </div>
                        <div class="form-group">
                            <label for="paystatus_id">Stock Quantity</label>
                            <input type="number" name="quantity"/>
                        </div>
                        <button type="submit" class="btn btn-primary" style="width: 100%">SAVE<div
                            class="ripple-container"></div>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @section('script')
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js" integrity="sha256-hlKLmzaRlE8SCJC1Kw8zoUbU8BxA+8kR3gseuKfMjxA=" crossorigin="anonymous"></script>
<script >
     $(document).ready(function(){
        src = "{{ route('searchajax') }}";
        $( "#seed_one" ).autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: src,
                    dataType: "json",
                    data: {
                        term: request.term
                    },
                    success: function (data) {
                        response(data);

                    }
                });
            },
            minLength: 3,
            select: function( event, ui ) {
                // Your autoComplete response returns the ID in the 'value' field
                // window.location = 'http://yoursite.com/products/' + ui.item.value
            }
        });
    });
 </script>
 @endsection
</x-app-layout>

resources/views/modules/stocks/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Stocks List') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <a href="{{ route('stocks.create') }}" class="btn btn-primary" style="float: right">ADD NEW STOCK<div
                class="ripple-container"></div>
            </a>
            <div class="bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                    @endif
                    <table>
                        <thead class=" text-primary">
                            <tr>
                                <th></th>
                                <th>Name</th>
                                <th class="">Brand</th>
                                <th class="">Price</th>
                                <th class="">Quantity</th>
                                <th class="">#</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($stockList as $stock)
                            <tr>
                                <td></td>
                                <td>{{ $stock->stock_name }}</td>
                                <td>{{ $stock->brand }}</td>
                                <td>{{ $stock->price }}</td>
                                <td>{{ $stock->quantity }}</td>
                                <td>#</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>