routes/web.php
<?php

use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\admin\TariffController;
use App\Http\Controllers\admin\OrderController;
use App\Http\Controllers\admin\ReportController;
use App\Http\Controllers\admin\CompanyInfoController;
use App\Http\Controllers\admin\TransactionController;
use App\Http\Controllers\admin\BookingController;
use App\Http\Controllers\admin\RecieptController;
use App\Http\Controllers\admin\ReservationController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\ImageGalleryController;
use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
    Route::group(['middleware' => 'HtmlMinifier'], function () {

        Route::get('/', [IndexController::class, 'index'])->name('index');

        Route::get('gallery', [ImageGalleryController::class, 'index'])->name('gallery');

        Route::get('explore', [IndexController::class, 'explore'])->name('explore');

        Route::get('tariff', [IndexController::class, 'tariff'])->name('tariff');

        Route::get('inquiry/{t_id}', [IndexController::class, 'bookingInquery'])->name('inquiry');

        Route::get('contactus', [IndexController::class, 'contactus'])->name('contactus');

        Route::get('thankyou', function () {
            return view('thankyou');
        })->name('thankyou');

        Route::prefix('book')->group(function () {
            Route::get('', [BookingController::class, 'index'])->name('bookingEngine');
            Route::post('user-details', [BookingController::class, 'userDetails'])->name('bookingEngine.user.details');
            Route::get('search', [BookingController::class, ''])->name('bookingEngine.room');
            Route::post('search-room', [BookingController::class, ''])->name('bookingEngine.room.save');
            Route::post('paytm-payment', [BookingController::class, 'paytmPayment'])->name('paytm.payment');
            Route::post('paytm-callback', [BookingController::class, 'paytmCallback'])->name('paytm.callback');
        });
    });


    // Route::get('contactus/reload-captcha', [IndexController::class, 'reloadCaptcha'])->name('contactus.captcha-reload');

    Route::post('contactus/save', [IndexController::class, 'savecontactUsData'])->name('contactus.save');

    Route::post('inquiry/{t_id}/save', [IndexController::class, 'bookingInquerySave'])->name('inquiry.save');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

    Route::prefix('dashboard')->middleware(['auth'])->group(function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

        // Staff Admin
        Route::middleware(['role:admin'])->group(function () {
            Route::get('product/list', [DashboardController::class, 'productlist'])->name('dashboard.products.list');
            Route::get('transaction', [TransactionController::class, 'index'])->name('dashboard.transaction.index');
            Route::get('transaction/create', [TransactionController::class, 'linkGenerate'])->name('dashboard.transaction.link.create');
            // Route::get('food/receipt/', [RecieptController::class, 'index'])->name('dashboard.receipt.index');

            Route::resource('company-info', CompanyInfoController::class);
            Route::prefix('receipt')->group(function () {
                // Route::get('reservation/{reservationId}', [ReservationController::class, 'show'])->name('dashboard.receipt.reservation.show');

                // Route::get('room/{bookingId}', [RecieptController::class, 'roomshow'])->name('dashboard.receipt.room.show');
            });

            Route::prefix('reservation')->group(function () {
                Route::get('', [ReservationController::class, 'index'])->name('dashboard.reservation.list');
                Route::get('new', [ReservationController::class, 'create'])->name('dashboard.reservation.new');
                Route::post('create', [ReservationController::class, 'store'])->name('dashboard.reservation.create');
                Route::get('{reservationId}', [ReservationController::class, 'show'])->name('dashboard.receipt.reservation.show');
                Route::get('room/receipt/{id}', [RecieptController::class, 'roomshow'])->name('dashboard.receipt.room.bill');
            });

            Route::resource('stocks', StockController::class);
        });

        // Staff Manager
        Route::middleware(['role:manager'])->group(function (){

        });

        // Staff Routes
        Route::middleware(['role:staff'])->group(function (){

        });

        Route::middleware(['role:admin|manager'])->group(function() {
            Route::get('gallery', [ImageGalleryController::class, 'index'])->name('dashboard.gallery.view');
            Route::get('gallery/create', [ImageGalleryController::class, 'create'])->name('dashboard.gallery.create');
            Route::post('gallery/store', [ImageGalleryController::class, 'upload'])->name('dashboard.gallery.upload');
        });

        Route::middleware(['role:admin|staff'])->group(function() {
            Route::resource('order', OrderController::class); // order.index
            Route::get('food/{foodId}', [RecieptController::class, 'show'])->name('dashboard.receipt.food.show');
            // Route::get('order/list/all', [OrderController::class, 'listOrder'])->name('dashboard.order.table');
            // Route::get('receipt', [ReportController::class, 'receiptShow'])->name('order.receipt');
        });

        Route::middleware(['role:admin|manager|staff'])->group(function() {
            Route::get('profile', [DashboardController::class, 'myprofile'])->name('dashboard.profile');
            Route::resource('tariff', TariffController::class);
        });

    });

    require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/modules/profile/company-info.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Company Info') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif
                    <form method="POST" action="{{ route('company-info.update', $companyinfo->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Company Name</label>
                                    <input type="text" class="form-control" value="{{ $companyinfo->company_name }}" required name="company_name">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Gst Charges(%)</label>
                                    <input type="number" class="form-control" value="{{ $companyinfo->gst }}" name="gst">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">State gst Charges(%)</label>
                                    <input type="number" class="form-control" value="{{ $companyinfo->sgst }}" name="sgst">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Central gst Charges(%)</label>
                                    <input type="number" class="form-control" value="{{ $companyinfo->cgst }}" name="cgst">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Address</label>
                                    <input type="text" class="form-control" required value="{{ $companyinfo->address }}" name="address">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Phone Number</label>
                                    <input type="tel" class="form-control" required value="{{ $companyinfo->phone }}" name="phone">
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">State</label>
                                    <input type="text" class="form-control" value="{{ $companyinfo->state }}" name="state" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Country</label>
                                    <input type="text" class="form-control" value="{{ $companyinfo->country }}" name="country" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Currency</label>
                                    <input type="text" class="form-control" value="{{ $companyinfo->currency  }}" name="currency" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="bmd-label-floating">Message</label>
                                    <input type="text" class="form-control" value="{{ $companyinfo->message  }}" name="message">
                                </div>
                            </div>
                            <button class="btn btn-info" type="submit">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/modules/profile/myprofile.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Profile') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header card-header-primary">
                                        <h4 class="card-title">Edit Profile</h4>
                                        <p class="card-category">Complete your profile</p>
                                    </div>
                                    <div class="card-body">
                                        <form>
                                            <div class="row">
                                                {{-- <div class="col-md-5">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">Company (disabled)</label>
                                                        <input type="text" class="form-control" disabled>
                                                    </div>
                                                </div> --}}
                                                <div class="col-md-3">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">Username</label>
                                                        <input type="text" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">Email address</label>
                                                        <input type="email" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">Fist Name</label>
                                                        <input type="text" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">Last Name</label>
                                                        <input type="text" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">Adress</label>
                                                        <input type="text" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">City</label>
                                                        <input type="text" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">Country</label>
                                                        <input type="text" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="bmd-label-floating">Postal Code</label>
                                                        <input type="text" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label>About Me</label>
                                                        <div class="form-group">
                                                            <label class="bmd-label-floating"> Lamborghini Mercy, Your
                                                                chick she so thirsty, I'm in that two seat
                                                                Lambo.</label>
                                                            <textarea class="form-control" rows="5"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary pull-right">Update
                                                Profile</button>
                                            <div class="clearfix"></div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>