routes/web.php
<?php

use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\admin\TariffController;
use App\Http\Controllers\admin\OrderController;
use App\Http\Controllers\admin\ReportController;
use App\Http\Controllers\admin\CompanyInfoController;
use App\Http\Controllers\admin\TransactionController;
use App\Http\Controllers\admin\BookingController;
use App\Http\Controllers\admin\RecieptController;
use App\Http\Controllers\admin\ReservationController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\ImageGalleryController;
use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
    Route::group(['middleware' => 'HtmlMinifier'], function () {

        Route::get('/', [IndexController::class, 'index'])->name('index');

        Route::get('gallery', [ImageGalleryController::class, 'index'])->name('gallery');

        Route::get('explore', [IndexController::class, 'explore'])->name('explore');

        Route::get('tariff', [IndexController::class, 'tariff'])->name('tariff');

        Route::get('inquiry/{t_id}', [IndexController::class, 'bookingInquery'])->name('inquiry');

        Route::get('contactus', [IndexController::class, 'contactus'])->name('contactus');

        Route::get('thankyou', function () {
            return view('thankyou');
        })->name('thankyou');

        Route::prefix('book')->group(function () {
            Route::get('', [BookingController::class, 'index'])->name('bookingEngine');
            Route::post('user-details', [BookingController::class, 'userDetails'])->name('bookingEngine.user.details');
            Route::get('search', [BookingController::class, ''])->name('bookingEngine.room');
            Route::post('search-room', [BookingController::class, ''])->name('bookingEngine.room.save');
            Route::post('paytm-payment', [BookingController::class, 'paytmPayment'])->name('paytm.payment');
            Route::post('paytm-callback', [BookingController::class, 'paytmCallback'])->name('paytm.callback');
        });
    });


    // Route::get('contactus/reload-captcha', [IndexController::class, 'reloadCaptcha'])->name('contactus.captcha-reload');

    Route::post('contactus/save', [IndexController::class, 'savecontactUsData'])->name('contactus.save');

    Route::post('inquiry/{t_id}/save', [IndexController::class, 'bookingInquerySave'])->name('inquiry.save');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

    Route::prefix('dashboard')->middleware(['auth'])->group(function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

        // Staff Admin
        Route::middleware(['role:admin'])->group(function () {
            Route::get('product/list', [DashboardController::class, 'productlist'])->name('dashboard.products.list');
            Route::get('transaction', [TransactionController::class, 'index'])->name('dashboard.transaction.index');
            Route::get('transaction/create', [TransactionController::class, 'linkGenerate'])->name('dashboard.transaction.link.create');
            // Route::get('food/receipt/', [RecieptController::class, 'index'])->name('dashboard.receipt.index');

            Route::resource('company-info', CompanyInfoController::class);
            Route::prefix('receipt')->group(function () {
                // Route::get('reservation/{reservationId}', [ReservationController::class, 'show'])->name('dashboard.receipt.reservation.show');

                // Route::get('room/{bookingId}', [RecieptController::class, 'roomshow'])->name('dashboard.receipt.room.show');
            });

            Route::prefix('reservation')->group(function () {
                Route::get('', [ReservationController::class, 'index'])->name('dashboard.reservation.list');
                Route::get('new', [ReservationController::class, 'create'])->name('dashboard.reservation.new');
                Route::post('create', [ReservationController::class, 'store'])->name('dashboard.reservation.create');
                Route::get('{reservationId}', [ReservationController::class, 'show'])->name('dashboard.receipt.reservation.show');
                Route::get('room/receipt/{id}', [RecieptController::class, 'roomshow'])->name('dashboard.receipt.room.bill');
            });

            Route::resource('stocks', StockController::class);
        });

        // Staff Manager
        Route::middleware(['role:manager'])->group(function (){

        });

        // Staff Routes
        Route::middleware(['role:staff'])->group(function (){

        });

        Route::middleware(['role:admin|manager'])->group(function() {
            Route::get('gallery', [ImageGalleryController::class, 'index'])->name('dashboard.gallery.view');
            Route::get('gallery/create', [ImageGalleryController::class, 'create'])->name('dashboard.gallery.create');
            Route::post('gallery/store', [ImageGalleryController::class, 'upload'])->name('dashboard.gallery.upload');
        });

        Route::middleware(['role:admin|staff'])->group(function() {
            Route::resource('order', OrderController::class); // order.index
            Route::get('food/{foodId}', [RecieptController::class, 'show'])->name('dashboard.receipt.food.show');
            // Route::get('order/list/all', [OrderController::class, 'listOrder'])->name('dashboard.order.table');
            // Route::get('receipt', [ReportController::class, 'receiptShow'])->name('order.receipt');
        });

        Route::middleware(['role:admin|manager|staff'])->group(function() {
            Route::get('profile', [DashboardController::class, 'myprofile'])->name('dashboard.profile');
            Route::resource('tariff', TariffController::class);
        });

    });

    require __DIR__ . '/auth.php';

app/Models/Reservation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reservation extends Model
{
    use HasFactory;
    protected $table = 'reservation';


    protected $fillable = [
        'reservation_number',
        'guestId',
        'roomId',
        'adultCount',
        'childCount',
        'checkin',
        'checkout',
        'nights',
        'advance_amount',
        'source',
        'total_amount',
        'sell_amount',
        'stay_status',
        'paid_amount'
    ];

    public function room() {
        return $this->hasMany('App\Models\Rooms', 'id', 'roomId');
    }

    public function guest() {
        return $this->belongsTo('App\Models\GuestDetails', 'guestId');
    }
}

app/Http/Controllers/admin/ReservationController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Rooms;
use App\Models\GuestDetails;
use App\Models\Reservation;
use PDF;

class ReservationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $reservationList = Reservation::with(['room', 'guest'])->orderBy('created_at', 'desc')->get();
        return view('modules.reservation.index', compact('reservationList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // create reservation and pdf for stating reservation
        $roomList = Rooms::get();
        return view('modules.reservation.make-reservation', compact('roomList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        DB::transaction(function () use ($request) {
            $reservation_number = Reservation::all()->last()->reservation_number + 1;
            foreach ($request->get('room') as $key => $value) {
            // dd($request->room, $request->get('room'), $value);
                $guestExist = GuestDetails::where('email', $request->email[$key])->first();
                if ($guestExist == null){
                    $userNewDetails = GuestDetails::create([
                        'name'      => $request->name[$key],
                        'email'     => $request->email[$key],
                        'contact'   => $request->phone[$key]
                    ]);
                    Reservation::create([
                        'reservation_number'=> $reservation_number,
                        'guestId'           => $userNewDetails->id,
                        'roomId'            => $value,
                        'adultCount'        => $request->adultCount[$key],
                        'childCount'        => $request->childCount[$key],
                        'checkin'           => $request->checkin[$key],
                        'checkout'          => $request->checkout[$key],
                        'nights'            => ceil(abs(strtotime($request->checkin[$key]) - strtotime($request->checkout[$key]))/ 86400),
                        'advance_amount'    => $request->advance_amount[$key],
                        'source'            => $request->source[$key],
                        'total_amount'      => $request->total_amount[$key],
                        'sell_amount'       => $request->sell_amount[$key],
                        'stay_status'       => 'Pending',
                        'paid_amount'       => $request->advance_amount[$key],
                    ]);
                } else {
                    Reservation::create([
                        'reservation_number'=> $reservation_number,
                        'guestId'           => $guestExist->id,
                        'roomId'            => $value,
                        'adultCount'        => $request->adultCount[$key],
                        'childCount'        => $request->childCount[$key],
                        'checkin'           => $request->checkin[$key],
                        'checkout'          => $request->checkout[$key],
                        'nights'            => ceil(abs(strtotime($request->checkin[$key]) - strtotime($request->checkout[$key]))/ 86400),
                        'advance_amount'    => $request->advance_amount[$key],
                        'source'            => $request->source[$key],
                        'total_amount'      => $request->total_amount[$key],
                        'sell_amount'       => $request->sell_amount[$key],
                        'stay_status'       => 'Pending',
                        'paid_amount'       => $request->advance_amount[$key],
                    ]);
                }
            }
        });
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $reservationList = Reservation::with(['room', 'guest'])->where('id', $id)->first();
        view()->share('reservationList',$reservationList);
        $dompdf = PDF::loadView('modules.reservation.view', $reservationList);

        // Output the generated PDF to Browser
        return $dompdf->stream();
        // return view('modules.reservation.view', compact('roomList'));
    }

    public function list() {
        $reservationList = Reservation::with(['room', 'guest'])->first();
        return view('modules.reservation.list', compact('reservationList'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($reservationId)
    {
        //

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/modules/reservation/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Reservation List') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                    @endif
                    <table>
                        <thead class=" text-primary">
                            <tr>
                                <th></th>
                                <th>Name</th>
                                <th class="">Room Name</th>
                                <th class="">Check In</th>
                                <th class="">Check Out</th>
                                <th class="">No of Nights</th>
                                <th class="">Advance Amount</th>
                                <th class="">Booking Source</th>
                                <th class="">#</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($reservationList as $key => $reservation)
                            <tr>
                                <td>
                                    {{ $key + 1 }}
                                </td>
                                <td>
                                    {{ $reservation->guest->name }}
                                </td>
                                <td>
                                    {{-- @foreach($reservation->room as $room) --}}
                                        {{ $reservation->room[0]->room_type }}
                                    {{-- @foreach --}}
                                </td>
                                <td class="">
                                    {{ $reservation->checkin }}
                                </td>
                                <td class="">
                                    {{ $reservation->checkout }}
                                </td>
                                <td class="">
                                    {{ $reservation->nights }}
                                </td>
                                <td>
                                    {{ $reservation->advance_amount }}
                                </td>
                                <td style="text-transform: uppercase">
                                    {{ $reservation->source }}
                                </td>
                                <td class="">
                                    {{-- <a class="btn btn-primary" href="{{ route('dashboard.receipt.reservation.show', $reservation->id) }}"
                                        role="button">Edit</a> --}}
                                    <a class="btn btn-primary" target="_blank" href="{{ route('dashboard.receipt.reservation.show', $reservation->id) }}"
                                        role="button">View</a>
                                        <a class="btn btn-success" target="_blank" href="{{ route('dashboard.receipt.room.bill', $reservation->reservation_number) }}"
                                            role="button">Print Bill</a>
                                    @permission('tariffs-delete')
                                    {{-- <button type="button" class="btn btn-sm btn-danger"
                                        onclick="event.preventDefault();document.getElementById('delete-user-form-{{$reservation->id}}').submit();">
                                        Delete
                                    </button>
                                    <form id="delete-user-form-{{$reservation->id}}"
                                        action="{{route('tariff.destroy', $reservation->id )}}" method="POST"
                                        style="display:none;">
                                        @csrf
                                        @method("DELETE")
                                    </form> --}}
                                    @endpermission
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/modules/reservation/make-reservation.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('New Reservation') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-12xl mx-auto sm:px-12 lg:px-12">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg" style="padding: 20px">
                <button class="btn btn-primary btn-round" style="width:100%" id="add_more_rooms">ADD ROOM</button>
                <form class="col s12" action="{{ route('dashboard.reservation.create') }}" method="post">
                    @csrf
                    <div id="customer_room_details">
                        <div style="border:3px solid; padding: 20px" class="resercation_section">
                            <div class="row">
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_prefix">Name</label>
                                        <input id="icon_prefix" type="text" name="name[]" required value="{{ old('name') }}">
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_email">Email</label>
                                        <input id="icon_email" type="email" name="email[]" required
                                            value="{{ old('email') }}">
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_telephone">Telephone</label>
                                        <input id="icon_telephone" type="tel" class="validate" name="phone[]" required
                                            value="{{ old('phone') }}">
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_guestCount">No of Adults</label>
                                        <input id="icon_guestCount" type="number" min="1" max="12" class="validate"
                                            name="adultCount[]" required value="{{ old('adultNumber') }}">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_guestCountChild">No of Childrens</label>
                                        <input id="icon_guestCountChild" type="number" min="1" max="12" class="validate"
                                            name="childCount[]" required value="{{ old('childNumber') }}">
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_guestCheckin">Check In Date</label>
                                        <input id="icon_guestCheckin" type="date" class="validate" name="checkin[]" required
                                            value="{{ old('guestNumber') }}">
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_guestCheckout">Check Out Date</label>
                                        <input id="icon_guestCheckout" type="date" class="validate" name="checkout[]" required
                                            value="{{ old('guestNumber') }}">
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_guestSource">Source</label>
                                        <select name="source[]" id="icon_guestSource" class="form-control" required>
                                            <option value="direct" selected>DIRECT</option>
                                            <option value="goibibo">GOIBIBO</option>
                                            <option value="mmt">MMT</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label class="" for="table_id">Select Room</label>
                                        <select name="room[]" id="table_id" class="form-control" required
                                            style="height:3.1rem;">
                                            <option value="" selected></option>
                                            @foreach( $roomList as $room )
                                            <option value="{{ $room->id }}">{{ $room->room_name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_guestpayment">Amount</label>
                                        <input id="icon_guestpayment" type="number" class="validate"
                                            name="total_amount[]" required value="{{ old('guestNumber') }}">
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_guestpayment">Sell Amount</label>
                                        <input id="icon_guestpayment" type="number" class="validate"
                                            name="sell_amount[]" required value="{{ old('guestNumber') }}">
                                    </div>
                                </div>
                                <div class="col s12 md3">
                                    <div class="form-group">
                                        <label for="icon_guestpayment">Advance Payment</label>
                                        <input id="icon_guestpayment" type="number" class="validate"
                                            name="advance_amount[]" required value="{{ old('guestNumber') }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br />
                    </div>
                    <div style="padding: 20px">
                        <div class="row book-button">
                            <div class="col s4">
                                <button class="btn btn-primary btn-round" style="width:100%">BOOK</button>
                            </div>
                            <div class="col s4">
                                <button class="btn btn-primary btn-round" style="width:100%">RESET</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @section('script')
    <script>
        $(document).ready(function () {
            $('#add_more_rooms').on('click', function () {
                var roomDiv = '';
                $('.resercation_section').clone().appendTo('#customer_room_details');

            });
            $('.customer_room_details').delegate('.delete', 'click', function () {
                if ($(this).parent().parent().parent().find('div').length > 1) {
                    $(this).parent().parent().remove();
                }
            });
        });
    </script>
    @endsection
</x-app-layout>