routes/web.php
<?php

use App\Http\Controllers\admin\DashboardController;
use App\Http\Controllers\admin\TariffController;
use App\Http\Controllers\admin\OrderController;
use App\Http\Controllers\admin\ReportController;
use App\Http\Controllers\admin\CompanyInfoController;
use App\Http\Controllers\admin\TransactionController;
use App\Http\Controllers\admin\BookingController;
use App\Http\Controllers\admin\RecieptController;
use App\Http\Controllers\admin\ReservationController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\ImageGalleryController;
use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
    Route::group(['middleware' => 'HtmlMinifier'], function () {

        Route::get('/', [IndexController::class, 'index'])->name('index');

        Route::get('gallery', [ImageGalleryController::class, 'index'])->name('gallery');

        Route::get('explore', [IndexController::class, 'explore'])->name('explore');

        Route::get('tariff', [IndexController::class, 'tariff'])->name('tariff');

        Route::get('inquiry/{t_id}', [IndexController::class, 'bookingInquery'])->name('inquiry');

        Route::get('contactus', [IndexController::class, 'contactus'])->name('contactus');

        Route::get('thankyou', function () {
            return view('thankyou');
        })->name('thankyou');

        Route::prefix('book')->group(function () {
            Route::get('', [BookingController::class, 'index'])->name('bookingEngine');
            Route::post('user-details', [BookingController::class, 'userDetails'])->name('bookingEngine.user.details');
            Route::get('search', [BookingController::class, ''])->name('bookingEngine.room');
            Route::post('search-room', [BookingController::class, ''])->name('bookingEngine.room.save');
            Route::post('paytm-payment', [BookingController::class, 'paytmPayment'])->name('paytm.payment');
            Route::post('paytm-callback', [BookingController::class, 'paytmCallback'])->name('paytm.callback');
        });
    });


    // Route::get('contactus/reload-captcha', [IndexController::class, 'reloadCaptcha'])->name('contactus.captcha-reload');

    Route::post('contactus/save', [IndexController::class, 'savecontactUsData'])->name('contactus.save');

    Route::post('inquiry/{t_id}/save', [IndexController::class, 'bookingInquerySave'])->name('inquiry.save');

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

    Route::prefix('dashboard')->middleware(['auth'])->group(function () {
        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

        // Staff Admin
        Route::middleware(['role:admin'])->group(function () {
            Route::get('product/list', [DashboardController::class, 'productlist'])->name('dashboard.products.list');
            Route::get('transaction', [TransactionController::class, 'index'])->name('dashboard.transaction.index');
            Route::get('transaction/create', [TransactionController::class, 'linkGenerate'])->name('dashboard.transaction.link.create');
            // Route::get('food/receipt/', [RecieptController::class, 'index'])->name('dashboard.receipt.index');

            Route::resource('company-info', CompanyInfoController::class);
            Route::prefix('receipt')->group(function () {
                // Route::get('reservation/{reservationId}', [ReservationController::class, 'show'])->name('dashboard.receipt.reservation.show');

                // Route::get('room/{bookingId}', [RecieptController::class, 'roomshow'])->name('dashboard.receipt.room.show');
            });

            Route::prefix('reservation')->group(function () {
                Route::get('', [ReservationController::class, 'index'])->name('dashboard.reservation.list');
                Route::get('new', [ReservationController::class, 'create'])->name('dashboard.reservation.new');
                Route::post('create', [ReservationController::class, 'store'])->name('dashboard.reservation.create');
                Route::get('{reservationId}', [ReservationController::class, 'show'])->name('dashboard.receipt.reservation.show');
                Route::get('room/receipt/{id}', [RecieptController::class, 'roomshow'])->name('dashboard.receipt.room.bill');
            });

            Route::resource('stocks', StockController::class);
        });

        // Staff Manager
        Route::middleware(['role:manager'])->group(function (){

        });

        // Staff Routes
        Route::middleware(['role:staff'])->group(function (){

        });

        Route::middleware(['role:admin|manager'])->group(function() {
            Route::get('gallery', [ImageGalleryController::class, 'index'])->name('dashboard.gallery.view');
            Route::get('gallery/create', [ImageGalleryController::class, 'create'])->name('dashboard.gallery.create');
            Route::post('gallery/store', [ImageGalleryController::class, 'upload'])->name('dashboard.gallery.upload');
        });

        Route::middleware(['role:admin|staff'])->group(function() {
            Route::resource('order', OrderController::class); // order.index
            Route::get('food/{foodId}', [RecieptController::class, 'show'])->name('dashboard.receipt.food.show');
            // Route::get('order/list/all', [OrderController::class, 'listOrder'])->name('dashboard.order.table');
            // Route::get('receipt', [ReportController::class, 'receiptShow'])->name('order.receipt');
        });

        Route::middleware(['role:admin|manager|staff'])->group(function() {
            Route::get('profile', [DashboardController::class, 'myprofile'])->name('dashboard.profile');
            Route::resource('tariff', TariffController::class);
        });

    });

    require __DIR__ . '/auth.php';

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $table = "orders";
    protected $fillable = [
        'name', 'address','table_id', 'pay_status', 'order_type'
    ];

    public function orderdetail() {
        return $this->hasMany('App\Models\Order_Detail');
    }

    public function room() {
        return $this->belongsTo('App\Models\Rooms', 'table_id');
    }

}

app/Http/Controllers/admin/OrderController.php
<?php


namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;

use App\Models\Order;
use App\Models\Products;
use App\Models\Rooms;
use App\Models\Order_Detail;
use App\Models\Cart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\App;
use \NumberFormatter;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('modules.order.index');
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $order_number = Order::all()->last()->id + 1;
        return view('modules.order.neworder', compact('order_number'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // return $request->all();

        DB::transaction(function() use ($request){
            // Order Model
            $order = new Order;
            $order->name = 'Luv Phogaat';
            $order->phone = '8447473921';
            $order->table_id = $request->table_id;
            $order->pay_status = 'pending';
            $order->pay_id = '';
            $order->order_type = 'ROOM';
            $order->save();
            $order_id = $order->id;

            // Order Details Modal
            for ($product = 0; $product < count($request->product_id); $product++){
                $order_details = new Order_Detail;
                $order_details->order_id = $order_id;
                $order_details->product_id = $request->product_id[$product];
                $order_details->quantity = $request->quantity[$product] ? $request->quantity[$product] : 1;
                $order_details->unitprice = $request->price[$product];
                $order_details->amount = $request->total_amount[$product];
                $order_details->save();
            }
            Cart::truncate();
        });
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show($orderId)
    {
        return view('modules.order.singleorder', compact('orderId'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
        // dd($request, $order);
        $order->fill($request->only([
            'pay_status'
        ]));
        $order->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }

    public function listOrder() {

        // $lastId = Order_Detail::max('order_id');
        // $order_receipt = Order_Detail::where('order_id', $lastId)->get();
        // $totalPrice = $this->totalAmount($order_receipt);
        // return view('modules.order.list');
    }

}

app/Http/Livewire/Orders/Index.php
<?php

namespace App\Http\Livewire\Orders;

use Livewire\Component;
use App\Models\Order;
use App\Models\Products;

class Index extends Component
{
    public $orders, $products = [], $rooms = [], $product_code, $message, $productInCart, $totalPrice, $ordersCom;


    public function mount() {
        $this->products = Products::all();
        $this->orders = Order::with(['orderdetail', 'room'])->where('pay_status', 'pending')->get();
        $this->ordersCom = Order::with(['orderdetail', 'room'])->where('pay_status', 'paid')->orderBy('created_at', 'desc')->get();
    }

    public function currencyFormatter($amount) {
        $formater =  new \NumberFormatter($locale = 'en_IN', \NumberFormatter::CURRENCY);
        return $formater->format($amount);
    }

    public function totalAmount($values) {
        $totalPrice = 0.00;
        foreach ($values as $key => $value) {
            $totalPrice += ($value-> product_qty * $value->product_price);
        }
        $formatter = new \NumberFormatter($locale = 'en_IN', \NumberFormatter::CURRENCY);
        return  $formatter->format($totalPrice);
    }


    public function render()
    {
        return view('livewire.orders.index');
    }
}

app/Http/Livewire/Orders/NewOrder.php
<?php

namespace App\Http\Livewire\Orders;

use Livewire\Component;
use App\Models\Products;
use App\Models\Rooms;
use App\Models\Cart;

class NewOrder extends Component
{
    public $orders, $products = [], $rooms = [], $product_code, $message, $productInCart, $totalPrice, $order_number, $pay_type ;


    public function mount($order_number) {
        $this->products = Products::orderBy('name', 'asc')->get();
        $this->rooms = Rooms::all();
        $this->productInCart = Cart::all();
        $this->totalPrice = $this->totalAmount($this->productInCart);
        $this->order_number = $order_number;
        $this->pay_type = 'pending';
        // dd($this->productInCart);
    }

    public function totalAmount($values) {
        $totalPrice = 0.00;
        foreach ($values as $key => $value) {
            $totalPrice += ($value-> product_qty * $value->product_price);
        }
        $formatter = new \NumberFormatter($locale = 'en_IN', \NumberFormatter::CURRENCY);
        return  $formatter->format($totalPrice);
    }

    public function InserttoCart() {
        $countProduct = Products::where('id', $this->product_code)->first();
        // dd($countProduct);
        $countCart = Cart::where('product_id', $this->product_code)->count();
        // if ($countCart > 0) {
        //     // increase the count
        //     $cartExistingProduct = Cart::where('product_id', $this->product_code)->first();
        //     $cartExistingProduct->product_qty = $cartExistingProduct->product_qty + 1;
        //     $cartExistingProduct->save();
        //     $this->productInCart = Cart::all();
        // }
        // else {
            $addToCart = new Cart;
            $addToCart->product_id = $countProduct->id;
            $addToCart->product_qty = 1;
            $addToCart->product_price = $countProduct->price;
            $addToCart->user_id = auth()->user()->id;
            $addToCart->save();
            $this->productInCart->prepend($addToCart);
        // }
        $this->product_code = '';
    }

    public function ChangeQty($orderDId,$eventvalue){
        if ( $eventvalue == 0 ) {
            $orderExistingProduct = Cart::where('id', $orderDId)->first();
            $orderExistingProduct->delete();
        } else {
            $orderExistingProduct = Cart::where('id', $orderDId)->first();
            $orderExistingProduct->product_qty = $eventvalue;
            $orderExistingProduct->save();
        }
        $this->productInCart = Cart::all();
    }

    public function removeProduct($cartId) {
        $deleteCart = Cart::find($cartId);
        $deleteCart->delete();
        $this->productInCart =  $this->productInCart->except($cartId);
    }

    public function currencyFormatter($amount) {
        $formater =  new \NumberFormatter($locale = 'en_IN', \NumberFormatter::CURRENCY);
        return $formater->format($amount);
    }


    public function render()
    {
        return view('livewire.orders.new-order');
    }
}

app/Http/Livewire/Orders/Order-old.php
<?php

namespace App\Http\Livewire;

use App\Models\Products;
use App\Models\Rooms;
use App\Models\Cart;
use Livewire\Component;

class Order extends Component
{
    // protected $listeners = [
    //     'InserttoCart',
    // ];
    public $orders, $products = [], $rooms = [], $product_code, $message, $productInCart, $totalPrice ;


    public function mount() {
        $this->products = Products::all();
        $this->rooms = Rooms::all();
        $this->productInCart = Cart::all();
        $this->totalPrice = $this->totalAmount($this->productInCart);
        // dd($this->productInCart);
    }

    public function totalAmount($values) {
        $totalPrice = 0.00;
        foreach ($values as $key => $value) {
            $totalPrice += ($value-> product_qty * $value->product_price);
        }
        $formatter = new \NumberFormatter($locale = 'en_IN', \NumberFormatter::CURRENCY);
        return  $formatter->format($totalPrice);
    }

    public function InserttoCart() {
        $countProduct = Products::where('id', $this->product_code)->first();
        // dd($countProduct);
        $countCart = Cart::where('product_id', $this->product_code)->count();
        if ($countCart > 0) {
            // increase the count
            $cartExistingProduct = Cart::where('product_id', $this->product_code)->first();
            $cartExistingProduct->product_qty = $cartExistingProduct->product_qty + 1;
            $cartExistingProduct->save();
            $this->productInCart = Cart::all();
        }
        else {
            $addToCart = new Cart;
            $addToCart->product_id = $countProduct->id;
            $addToCart->product_qty = 1;
            $addToCart->product_price = $countProduct->price;
            $addToCart->user_id = auth()->user()->id;
            $addToCart->save();
            $this->productInCart->prepend($addToCart);
        }
        $this->product_code = '';
    }

    public function IncrementQty($cartId){


    }

    public function DecrementQty($cartId){


    }

    public function removeProduct($cartId) {
        $deleteCart = Cart::find($cartId);
        $deleteCart->delete();
        $this->productInCart =  $this->productInCart->except($cartId);
    }

    public function currencyFormatter($amount) {
        $formater =  new \NumberFormatter($locale = 'en_IN', \NumberFormatter::CURRENCY);
        return $formater->format($amount);
    }

    public function render()
    {
        return view('livewire.order.neworder');
    }
}

resources/views/livewire/orders/index.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header purple text-white">
                    <h3>Current Orders</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table tableed" cellspacing="20" cellpadding="20">
                            <thead class=" text-primary">
                                <th>Sno</th>
                                <th width="40%">
                                    Room Name
                                </th>
                                <th>
                                    Total Amount
                                </th>
                                <th>
                                    Status
                                </th>
                                <!-- <th>
                                    Dis (%)
                                </th> -->
                                <th colspan="6">
                                    #
                                </th>
                            </thead>
                            <tbody class="addMoreProduct">
                                @foreach($orders as $key => $order)
                                {{-- {{ dd($order) }} --}}
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td width="40%">
                                        <div class="form-outline">
                                            {{ $order->room->room_name }}
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-outline">
                                            {{-- <input type="number" name="quantity[]" id="quantity"
                                                class="form-control quantity custom-text-css"
                                                value="{{ $cart->product_qty }}" min="0" /> --}}
                                                {{ $this->currencyFormatter($order->orderdetail->sum('amount')  ) }}
                                        </div>
                                    </td>
                                    <td width="15%">
                                        <div class="form-outline" style="text-transform: uppercase">
                                            {{-- <input type="number" name="price[]" id="price"
                                                value="{{ $cart->product_price }}"
                                                class="form-control price custom-text-css" /> --}}
                                                {{ $order->pay_status }}
                                        </div>
                                    </td>
                                    <td class="text-center" width="10%">
                                        <!-- <a href="#" class="btn btn-danger delete">
                                                <i class="material-icons" wire:click="removeProduct({{ $order->id }})">close</i>
                                            </a> -->
                                        {{-- <button type="button" rel="tooltip" class="btn btn-danger btn-sm">
                                            <i class="material-icons"
                                                wire:click="removeProduct({{ $order->id }})">close</i>
                                        </button> --}}
                                        <a href="{{ route('order.show', $order->id) }}" class="btn btn-success">
                                            <i class="material-icons">add</i>Add More
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header purple text-white">
                    <h3>Completed Orders</h3>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table tableed" cellspacing="20" cellpadding="20">
                            <thead class=" text-primary">
                                <th>Sno</th>
                                <th width="40%">
                                    Room Name
                                </th>
                                <th>
                                    Total Amount
                                </th>
                                <th>
                                    Status
                                </th>
                                <!-- <th>
                                    Dis (%)
                                </th> -->
                                <th colspan="6">
                                    #
                                </th>
                            </thead>
                            <tbody class="addMoreProduct">
                                @foreach($ordersCom as $key => $order)
                                {{-- {{ dd($order) }} --}}
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td width="40%">
                                        <div class="form-outline">
                                            {{ $order->room->room_name }} - {{ $order->name }}
                                        </div>
                                    </td>
                                    <td>
                                        <div class="form-outline">
                                            {{-- <input type="number" name="quantity[]" id="quantity"
                                                class="form-control quantity custom-text-css"
                                                value="{{ $cart->product_qty }}" min="0" /> --}}
                                                {{ $this->currencyFormatter($order->orderdetail->sum('amount')  ) }}
                                        </div>
                                    </td>
                                    <td width="15%">
                                        <div class="form-outline" style="text-transform: uppercase">
                                            {{-- <input type="number" name="price[]" id="price"
                                                value="{{ $cart->product_price }}"
                                                class="form-control price custom-text-css" /> --}}
                                                {{ $order->pay_status }}
                                        </div>
                                    </td>
                                    <td class="text-center" width="10%">
                                        <!-- <a href="#" class="btn btn-danger delete">
                                                <i class="material-icons" wire:click="removeProduct({{ $order->id }})">close</i>
                                            </a> -->
                                        {{-- <button type="button" rel="tooltip" class="btn btn-danger btn-sm">
                                            <i class="material-icons"
                                                wire:click="removeProduct({{ $order->id }})">close</i>
                                        </button> --}}
                                        <a href="{{ route('order.show', $order->id) }}" class="btn btn-success">
                                            View
                                        </a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>